//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiaNet.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PredMap {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PredMap() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SiaNet.Common.Resources.PredMap", typeof(PredMap).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0: &apos;airplane&apos;,
        /// 1: &apos;automobile&apos;,
        /// 2: &apos;bird&apos;,
        /// 3: &apos;cat&apos;,
        /// 4: &apos;deer&apos;,
        /// 5: &apos;dog&apos;,
        /// 6: &apos;frog&apos;,
        /// 7: &apos;horse&apos;,
        /// 8: &apos;ship&apos;,
        /// 9: &apos;truck&apos;
        ///}.
        /// </summary>
        public static string Cifar10 {
            get {
                return ResourceManager.GetString("Cifar10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0: &apos;tench, Tinca tinca&apos;,
        /// 1: &apos;goldfish, Carassius auratus&apos;,
        /// 2: &apos;great white shark, white shark, man-eater, man-eating shark, Carcharodon carcharias&apos;,
        /// 3: &apos;tiger shark, Galeocerdo cuvieri&apos;,
        /// 4: &apos;hammerhead, hammerhead shark&apos;,
        /// 5: &apos;electric ray, crampfish, numbfish, torpedo&apos;,
        /// 6: &apos;stingray&apos;,
        /// 7: &apos;cock&apos;,
        /// 8: &apos;hen&apos;,
        /// 9: &apos;ostrich, Struthio camelus&apos;,
        /// 10: &apos;brambling, Fringilla montifringilla&apos;,
        /// 11: &apos;goldfinch, Carduelis carduelis&apos;,
        /// 12: &apos;house finch, linnet, Carpodacus mexicanus&apos;,
        /// 13: &apos;junco, snow [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ImageNet1K {
            get {
                return ResourceManager.GetString("ImageNet1K", resourceCulture);
            }
        }
    }
}
